services:
  # nginx:
  #   build: ./nginx
  #   ports:
  #     - "3001:9999"
  #   networks:
  #   - gitlab-network
  # backend:
  #   hostname: 'backend'
  #   command: ["./plim-rusty"]
  #   build: .
  #   environment:
  #     ADMIN_GL_TOKEN: "glpat-TTr9G3yHut_kRxXRgLFh"
  #     TOKEN_SECRET: "your secret"
  #   networks:
  #     - gitlab-network
  #   volumes:
  #     - ./config:/app/config
  #     - ./config.yml:/app/config.yml
  etcd:
    image: bitnami/etcd:3.5.10
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - gitlab-network
# localhost:8080/etcdkeeper/
  etcd-ui:
    image:  evildecay/etcdkeeper:v0.7.6
    ports:
      - "8080:8080"
    networks:
      - gitlab-network
      
networks:
  gitlab-network:
    name: gitlab-network