# open https://localhost:3000/ to see the frontend
# open http://localhost:8080/etcdkeeper/ to see the etcdkeeper ui
services:
  nginx:
    build: ./nginx
    ports:
      - "3000:3000"
    networks:
    - gitlab-network
    depends_on:
      - backend
  backend:
    image: ghcr.io/ontonny/plim:latest
    hostname: 'backend'
    build: .
    environment:
      ADMIN_GL_TOKEN: "glpat-TTr9G3yHut_kRxXRgLFh"
      TOKEN_SECRET: "your secret"
      RUST_BACKTRACE: 1 
    networks:
      - gitlab-network
    volumes:
      - ./config:/app/config
      - ./config.yml:/app/config.yml
  etcd:
    hostname: 'etcd'
    image: bitnami/etcd:3.5.10
    command: /opt/bitnami/scripts/etcd/entrypoint.sh /opt/bitnami/scripts/etcd/run.sh
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - gitlab-network
  etcd_migration:
    image: bitnami/etcd:3.5.10
    command: sh /etcd_migrations/run.sh
    volumes:
      - ./etcd_migrations:/etcd_migrations
    networks:
      - gitlab-network
  etcd-ui:
    image:  evildecay/etcdkeeper:v0.7.6
    command: /bin/sh -c ./etcdkeeper.bin -h 127.0.0.1 -p 8080
    ports:
      - "8080:8080"
    networks:
      - gitlab-network


networks:
  gitlab-network:
    name: gitlab-network