plans:
  example-ansible-create-yaml:
    type: gitlab-ansible-base64
    groups: [test,admin, other]
    ansible:
      backend_inventory:
        type: local
        file_path: "config/ansible/test2.yml"
      vault_pass_file: ""
      tags: []
      limit: []
      ask_vault_password:
      check: false
      diff: true
      private_key: ~/.ssh/id_rsa
      playbook: my_playbook.yml
      inventory: ansible/prod/small.yml
      syntax_check: false
      forks: 5
      verbosity: 0
    gitlab:
      project_id: 1
      token_var: ADMIN_GL_TOKEN # need to pass from system variables to process
      ref: main
      execute_api_type: create
      json_data_key: ansible_base64
      ref_select:
        ref_select_enabled: true
        branch_enabled: false
        branch_search_name: test
        branch_regex: ~
        tag_enabled: true
        tag_search_name: ~
        tag_regex: ^tag
    views:
      - text: "boolean test"
        type: checkbox
        key: "TEST_CHECKBOX"
        value: true
      - text: "radio test"
        type: radio
        key: "TEST_RADIO"
        data: ["1", "2", "3", "4"]
        value: "3"
      - text: "select test"
        type: select
        key: "TEST_SELECT"
        data: ["Male", "Female", "Human", "Animal"]
        value: "Female"
      - text: "input test"
        type: input-field
        key: "TEST_INPUT"
        value: "my test input here"
      - text: "password test"
        type: password-input-field
        key: "TEST_PASSWD"
        value: "pass"
      - text: "hiddent test"
        type: hidden
        key: "TEST_HIDDEN"
        value: "test test"
      - text: "hiddent port"
        type: hidden
        key: "ansible_port"
        value: "22"
      - text: "hiddent user"
        type: hidden
        key: "ansible_ssh_user"
        value: "root"
