plans:
  example-ansible-etcd:
    type: gitlab-ansible-base64
    groups: [test,admin, other]
    ansible:
      backend_inventory:
        type: local
        file_path: "config/ansible/small.ini"
      vault_pass_file: ""
      tags: []
      limit: []
      ask_vault_password:
      check: false
      diff: true
      private_key: ~/.ssh/id_rsa
      playbook: my_playbook.yml
      inventory: ansible/prod/small.yml
      syntax_check: false
      forks: 5
      verbosity: 0
    gitlab:
      project_id: 1
      token_var: ADMIN_GL_TOKEN # need to pass from system variables to process
      ref: main
      execute_api_type: create
      json_data_key: ansible_base64
      allow_ref_select: true
    views:
      - text: "radio test static"
        type: radio
        key: "TEST_RADIO_STATIC"
        data: ["1", "2", "3", "4"]
        value: "3"
      - text: "radio test etcd"
        type: radio
        key: "TEST_RADIO"
        data: []
        data_source:
          type: etcd
          etcd_name: "test"
          key_path: /test/key
        value: "3"
      - text: "select test etcd"
        type: select
        key: "TEST_SELECT"
        data: []
        data_source:
          type: etcd
          etcd_name: "test"
          key_path: "/test/key2"
        value: "1"
      - text: "input test"
        type: input-field
        key: "TEST_INPUT"
        value: "my test input here"
        data_source:
          type: etcd
          etcd_name: "test"
          key_path: "/test/key3"
