plans:
  example-base64-trigger:
    name: example-base64-trigger
    type: gitlab-base64
    groups: [other]
    gitlab:
      project_id: 1
      token_var: TEST_TRIGGER_TOKEN
      ref: main
      execute_api_type: trigger
      json_data_key: "variables[jsonbase64]"
    views:
      - text: "boolean test"
        type: checkbox
        key: "TEST_CHECKBOX"
        value: true
      - text: "radio test"
        type: radio
        key: "TEST_RADIO"
        data: ["1", "2", "3", "4"]
        value: "3"
      - text: "select test"
        type: select
        key: "TEST_SELECT"
        data: ["Male", "Female", "Human", "Animal"]
        value: "Female"
      - text: "input test"
        type: input-field
        key: "TEST_INPUT"
        value: "my test input here"
      - text: "password test"
        type: password-input-field
        key: "TEST_PASSWD"
        value: "pass"
      - text: "hiddent test"
        type: hidden
        key: "TEST_HIDDEN"
        value: "test test"
